id: P008164
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 13:05:28.854382
source_metadata:
  id: bdr:W4CZ1687
  title: ཁྲི་ཆེན་བྱང་ཆུབ་ཆོས་འཕེལ་གྱི་རྣམ་ཐར་དགའ་ལྡན་བསྟན་པའི་མཛེས་རྒྱན།
  author: ''
  volumes:
    cff03a2ea6fd4cb4a0871661b135e08b:
      image_group_id: I1KG6102
      title: ''
      volume_number: 1
      total_pages: 477
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
