id: I4B449FB4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T08:15:34+00:00'
last_modified: '2022-06-09T04:56:39.735644+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ1687
  title: ཁྲི་ཆེན་བྱང་ཆུབ་ཆོས་འཕེལ་གྱི་རྣམ་ཐར་དགའ་ལྡན་བསྟན་པའི་མཛེས་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    64B2:
      image_group_id: I1KG6102
      title: ''
      total_pages: 477
      order: 1
      base_file: 64B2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
