id: I4B449FB4
legacy_id: P008164
ocr_import_info:
  bdrc_scan_id: W4CZ1687
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T08:14:57'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T18:24:58.054869+00:00'
last_modified: 2022-09-04 02:25:12.054207
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ1687
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ1687
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཁྲི་ཆེན་བྱང་ཆུབ་ཆོས་འཕེལ་གྱི་རྣམ་ཐར་དགའ་ལྡན་བསྟན་པའི་མཛེས་རྒྱན།
  author: རྒྱལ་དབང་ཆོས་རྗེ་བློ་བཟང་འཕྲིན་ལས་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.6381435505117206
  ocr_word_median_confidence_index: 0.7099999785423279
quality: null
bases:
  I1KG6102:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG6102
      total_pages: 477
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG6102.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.6381435505117206
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
